name: Test

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 0xPolygon/kurtosis-cdk@v0.2.3

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 0xPolygon/kurtosis-cdk@main

  debug-rachit77-erigon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 0xPolygon/kurtosis-cdk@rachit77/erigon

  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 0xPolygon/kurtosis-cdk@debug.4 # <https://github.com/0xPolygon/kurtosis-cdk/pull/204> leovct:ci/fix-regression-test-action
