name: Test

on:
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 0xPolygon/kurtosis-cdk@v0.2.3

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 0xPolygon/kurtosis-cdk@main
